name: Jes build
# Trigger the workflow on push or pull request
on: [push, pull_request]
jobs:
  build:
    name: Build from source, run checkstyle & tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Build with Maven & generate javadocs
        run: mvn clean install --file pom.xml -DskipTests=true
      - name: Run tests
        run: mvn test
      - uses: codecov/codecov-action@v1.0.2
        with:
          token: ${{secrets.CODECOV_TOKEN}}
      - name: Sonar report
        run: mvn verify sonar:sonar -Dsonar.login=${{secrets.SONAR_TOKEN}} -DskipTests=true
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
